---
title: "Examine Life Expectancy"
author: "Richard Ressler"
date: "`r Sys.Date()`"
output: pdf_document
urlcolor: "blue"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE}
library(tidyverse)
library(gapminder)
library(ggplot2)
```

# Abstract

Here, I re-examine the analysis of Oeppen and Vaupel (2002).

This is summarizing the data to be clean
# life expectency Analysis
```{r}
data("gapminder_unfiltered")
gapminder_unfiltered %>% 
  group_by(year) %>% 
  filter(lifeExp == max(lifeExp)) %>% 
  ungroup() %>% 
  select(year, country, lifeExp) %>% 
  arrange(year) ->
  sumdat
sumdat
```

#Edit your partner’s file to add code to create a scatterplot of year versus maximum life expectancy. Color code by country, and add a single Ordinary Least Squares (OLS) line.

```{r}
ggplot(data = sumdat) +
  geom_point(mapping = aes(x = year, y = lifeExp, color = country, )) +
  geom_smooth(aes(x = year, y = lifeExp), method = lm, se = FALSE) +
  xlab("Year") +
  ylab("Maximum Life Expectancy")
  
```

